# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      public
url:              http://developer.russet.in
encoding:         UTF-8

gems:
  - jekyll-sitemap

# site version
version: 1.0.0

# your github username
github_username: russetechsol
