# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# title: Your awesome title
# email: your-email@domain.com
# description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# Build settings
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# your informations
author:
  name: Sandeep Sihari
  description:
  picture: /_assets/images/avatar.jpg
  favicon: /_assets/images/favicon.png

# site description
description: Developer portal of Russet Technology Solutions LLP.

# site url
url: http://developer.russet.in

# site title
title: Russet

# site version
version: 1.0.0

# number of posts per page
paginate: 10

# your github username
github_username: russetechsol

# set true to include or false to exclude share option
share:
  twitter: true
  facebook: true
  google_plus: true
  linkedin: true
  disqus: true

source: src
destination: public
  
# if share.facebook is true, provide your facebook app id
facebook_app_id: 1139759226152493

# if share.disqus is true, provide your disqus shortname, the api key and the number of comments to display
disqus_username: russetechsol
# disqus_api_key: o2szu05bLNqiXiRvqe2oFvIHYYVR24eVkQiGs5WHcj0VUnvF8GCqD9HQUZErwCe7
# disqus_recent_comments_to_display: 5

# google analytics ID
# google_analytics_id: UA-58186085-1

markdown: kramdown
highlighter: rouge
exclude: [ 'README.md', 'src/', 'node_modules', 'package.json', 'Gruntfile.js' ]
excerpt_separator: <!--excerpt_separator-->

# Gems
gems: [jekyll-paginate]
